
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

            #include <glib-object.h>


            G_BEGIN_DECLS

/* enumerations from "fp-device.h" */


GType fp_device_type_get_type (void);
#define FP_TYPE_DEVICE_TYPE (fp_device_type_get_type())


GType fp_device_feature_get_type (void);
#define FP_TYPE_DEVICE_FEATURE (fp_device_feature_get_type())


GType fp_scan_type_get_type (void);
#define FP_TYPE_SCAN_TYPE (fp_scan_type_get_type())


GType fp_temperature_get_type (void);
#define FP_TYPE_TEMPERATURE (fp_temperature_get_type())


GType fp_device_retry_get_type (void);
#define FP_TYPE_DEVICE_RETRY (fp_device_retry_get_type())


GType fp_device_error_get_type (void);
#define FP_TYPE_DEVICE_ERROR (fp_device_error_get_type())

/* enumerations from "fp-print.h" */


GType fp_finger_get_type (void);
#define FP_TYPE_FINGER (fp_finger_get_type())


GType fp_finger_status_flags_get_type (void);
#define FP_TYPE_FINGER_STATUS_FLAGS (fp_finger_status_flags_get_type())

G_END_DECLS

/* Generated data ends here */

